#define PROJECT_VERSION_MAJOR 2
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 1
#define PROJECT_VERSION_BUILD 1845

#define STR(value) #value
#define STRINGIZE(value) STR(value)

#define PROJECT_VERSION_DOTTED_STRING \
  STRINGIZE(PROJECT_VERSION_MAJOR) "." \
  STRINGIZE(PROJECT_VERSION_MINOR) "." \
  STRINGIZE(PROJECT_VERSION_PATCH) "." \
  STRINGIZE(PROJECT_VERSION_BUILD)

#define PROJECT_NAME 
