#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 17
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION_BUILD 1

#define STR(value) #value
#define STRINGIZE(value) STR(value)

#define PROJECT_VERSION_DOTTED_STRING \
  STRINGIZE(PROJECT_VERSION_MAJOR) "." \
  STRINGIZE(PROJECT_VERSION_MINOR) "." \
  STRINGIZE(PROJECT_VERSION_PATCH) "." \
  STRINGIZE(PROJECT_VERSION_BUILD)

#define PROJECT_NAME Telecontrol SCADA
